import React, { useState, useEffect } from 'react';
import { BrainCircuit, Sparkles, Send, Loader2, BookOpen, Clock, Target, CheckCircle2, Plus, Trash2, RefreshCw } from 'lucide-react';
import { plannerService, taskService } from '../services/api';

const AIPlanner = ({ showToast }) => {
    const [loading, setLoading] = useState(false);
    const [goal, setGoal] = useState('');
    const [subject, setSubject] = useState('');
    const [duration, setDuration] = useState('1');
    const [generatedPlan, setGeneratedPlan] = useState(null);
    const [error, setError] = useState(null);
    const [saving, setSaving] = useState(false);
    const [saved, setSaved] = useState(false);
    const [savedPlans, setSavedPlans] = useState([]);
    const [loadingPlans, setLoadingPlans] = useState(false);

    useEffect(() => {
        loadSavedPlans();
    }, []);

    const loadSavedPlans = async () => {
        setLoadingPlans(true);
        try {
            const data = await plannerService.getAll();
            setSavedPlans(data);
        } catch (err) {
            console.error('Failed to load plans:', err);
        } finally {
            setLoadingPlans(false);
        }
    };

    const handleGenerate = async () => {
        setLoading(true);
        setError(null);
        setSaved(false);
        try {
            const plan = await plannerService.generate({
                subject,
                goal,
                duration: parseInt(duration)
            });
            setGeneratedPlan(plan);
        } catch (err) {
            console.error(err);
            setError(err.message || 'Failed to generate study plan. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleDeletePlan = async (id, planSubject) => {
        if (!window.confirm(`Are you sure you want to delete this plan? This will also remove the tasks for "${planSubject}" from your calendar and study room.`)) return;
        try {
            await plannerService.delete(id);
            showToast('Study plan and associated tasks deleted.');
            loadSavedPlans(); // Refresh the list

            // Clean up subject from local storage if it was auto-added
            const storedSubjects = JSON.parse(localStorage.getItem('studyai_subjects') || '[]');
            const filteredSubjects = storedSubjects.filter(s => s.name.toLowerCase() !== planSubject.toLowerCase());
            localStorage.setItem('studyai_subjects', JSON.stringify(filteredSubjects));
        } catch (err) {
            console.error(err);
            showToast('Failed to delete plan.', 'error');
        }
    };

    const handleSavePlan = async () => {
        if (!generatedPlan) return;
        setSaving(true);
        try {
            // Auto-sync subject to local storage
            const storedSubjects = JSON.parse(localStorage.getItem('studyai_subjects') || '[]');
            const existingSubject = storedSubjects.find(s => s.name.toLowerCase() === subject.toLowerCase());
            if (!existingSubject) {
                const newId = storedSubjects.length > 0 ? Math.max(...storedSubjects.map(s => s.id)) + 1 : 1;
                storedSubjects.push({
                    id: newId,
                    name: subject,
                    emoji: '💡',
                    colorIdx: Math.floor(Math.random() * 8),
                    hoursGoal: parseInt(duration) * 5,
                    notes: `Autogenerated: ${goal}`,
                    priority: 'High'
                });
                localStorage.setItem('studyai_subjects', JSON.stringify(storedSubjects));
            }

            for (const module of generatedPlan.modules) {
                const taskDate = new Date();
                taskDate.setDate(taskDate.getDate() + (module.dayOffset || 0));

                await taskService.create({
                    title: module.name,
                    subject: subject,
                    time: module.time,
                    description: module.topics.join(', '),
                    date: taskDate.toISOString(),
                    videoUrl: module.videoUrl
                });
            }
            setSaved(true);
            showToast('Study plan saved to your dashboard & calendar!');
        } catch (err) {
            console.error(err);
            showToast('Failed to save some modules. Please try again.', 'error');
        } finally {
            setSaving(false);
        }
    };

    return (
        <div style={{ maxWidth: '56rem', margin: '0 auto' }} className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="text-center space-y-4">
                <div className="inline-flex p-3 rounded-2xl bg-indigo-500/10 text-indigo-400 mb-2">
                    <BrainCircuit size={32} />
                </div>
                <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">AI Study Architect</h1>
                <p className="text-slate-400 max-w-lg mx-auto">Tell us what you want to learn, and our AI will build a personalized roadmap just for you.</p>
            </div>

            <div className="glass-card p-6 md:p-10 relative overflow-hidden">
                <div className="absolute top-0 right-0 p-8 text-indigo-500/10 pointer-events-none">
                    <Sparkles size={120} />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 relative" style={{ zIndex: 10 }}>
                    <div className="space-y-6">
                        <div className="space-y-2">
                            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                                <BookOpen size={16} style={{ color: '#818cf8' }} />
                                What subject are you studying?
                            </label>
                            <input
                                type="text"
                                placeholder="e.g. Quantum Computing, React.js, Organic Chemistry"
                                style={{
                                    width: '100%',
                                    backgroundColor: 'rgba(30, 41, 59, 0.8)',
                                    border: '1px solid rgba(255,255,255,0.12)',
                                    borderRadius: '12px',
                                    padding: '12px 16px',
                                    color: '#f8fafc',
                                    outline: 'none',
                                    fontSize: '15px',
                                }}
                                value={subject}
                                onChange={(e) => setSubject(e.target.value)}
                            />
                        </div>

                        <div className="space-y-2">
                            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                                <Clock size={16} style={{ color: '#818cf8' }} />
                                Duration (Weeks)
                            </label>
                            <select
                                style={{
                                    width: '100%',
                                    backgroundColor: 'rgba(30, 41, 59, 0.95)',
                                    border: '1px solid rgba(255,255,255,0.12)',
                                    borderRadius: '12px',
                                    padding: '12px 16px',
                                    color: '#f8fafc',
                                    outline: 'none',
                                    fontSize: '15px',
                                    appearance: 'none',
                                    cursor: 'pointer',
                                }}
                                value={duration}
                                onChange={(e) => setDuration(e.target.value)}
                            >
                                <option value="1">1 Week Intensive</option>
                                <option value="2">2 Weeks Balanced</option>
                                <option value="4">4 Weeks Comprehensive</option>
                                <option value="8">8 Weeks Deep Dive</option>
                            </select>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div className="space-y-2">
                            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', fontWeight: 600, color: '#cbd5e1' }}>
                                <Target size={16} style={{ color: '#818cf8' }} />
                                What's your specific goal?
                            </label>
                            <textarea
                                placeholder="e.g. I want to build a full-stack app from scratch"
                                style={{
                                    width: '100%',
                                    backgroundColor: 'rgba(30, 41, 59, 0.8)',
                                    border: '1px solid rgba(255,255,255,0.12)',
                                    borderRadius: '12px',
                                    padding: '12px 16px',
                                    color: '#f8fafc',
                                    outline: 'none',
                                    fontSize: '15px',
                                    height: '160px',
                                    resize: 'none',
                                    lineHeight: '1.6',
                                }}
                                value={goal}
                                onChange={(e) => setGoal(e.target.value)}
                            />
                        </div>
                    </div>
                </div>

                <button
                    onClick={handleGenerate}
                    disabled={loading || !subject || !goal}
                    className="w-full mt-10 btn-primary flex items-center justify-center gap-3 py-4 disabled:opacity-50 disabled:cursor-not-allowed group relative overflow-hidden"
                >
                    {loading ? (
                        <>
                            <Loader2 className="animate-spin" size={20} />
                            Generating your masterpiece...
                        </>
                    ) : (
                        <>
                            <Sparkles size={20} />
                            Generate Study Plan
                            <div className="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
                        </>
                    )}
                </button>
            </div>

            {error && (
                <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-400 text-sm font-medium">
                    {error}
                </div>
            )}

            {generatedPlan && (
                <div className="space-y-6 animate-in fade-in zoom-in-95 duration-500">
                    <div className="flex items-center gap-4">
                        <div className="h-px flex-1 bg-white/10" />
                        <h2 className="text-sm font-bold text-slate-500 uppercase tracking-widest">Plan Generated</h2>
                        <div className="h-px flex-1 bg-white/10" />
                    </div>

                    <div className="glass-card p-8 border-indigo-500/20">
                        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '24px', gap: '16px' }}>
                            <div>
                                <h2 className="text-xl md:text-2xl font-bold text-white">{generatedPlan.title}</h2>
                                <p className="text-slate-400 mt-2 text-sm md:text-base">{generatedPlan.overview}</p>
                            </div>
                            <button
                                onClick={handleSavePlan}
                                disabled={saving || saved}
                                style={{
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '8px',
                                    padding: '12px 24px',
                                    borderRadius: '12px',
                                    fontWeight: 700,
                                    whiteSpace: 'nowrap',
                                    border: saved ? '1px solid rgba(52,211,153,0.3)' : 'none',
                                    backgroundColor: saved ? 'rgba(16,185,129,0.15)' : '#4f46e5',
                                    color: saved ? '#34d399' : '#fff',
                                    cursor: saved ? 'default' : 'pointer',
                                    transition: 'all 0.2s',
                                    flexShrink: 0,
                                }}
                            >
                                {saving ? (
                                    <Loader2 size={18} className="animate-spin" />
                                ) : saved ? (
                                    <CheckCircle2 size={18} />
                                ) : (
                                    <Plus size={18} />
                                )}
                                {saving ? 'Saving...' : saved ? 'Saved!' : 'Save to Dashboard'}
                            </button>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                            {generatedPlan.modules.map((module, i) => (
                                <div key={i} className="p-5 rounded-2xl bg-white/5 border border-white/5 hover:border-indigo-500/30 transition-all group">
                                    <span className="text-xs font-bold text-indigo-400 mb-2 block">{module.time}</span>
                                    <h4 className="font-bold text-white mb-3 group-hover:text-indigo-300 transition-colors">{module.name}</h4>
                                    <ul className="space-y-2">
                                        {module.topics.map((topic, j) => (
                                            <li key={j} className="text-sm text-slate-400 flex items-center gap-2">
                                                <div className="w-1 h-1 rounded-full bg-slate-600 flex-shrink-0" />
                                                {topic}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Premium Strategic Vault - Robust Inline Styles */}
            <div style={{ marginTop: '80px', paddingTop: '60px', borderTop: '1px solid rgba(255,255,255,0.05)', position: 'relative' }}>
                <div style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: '200px', height: '1px', background: 'linear-gradient(90deg, transparent, #6366f1, transparent)' }} />

                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '32px', flexWrap: 'wrap', gap: '20px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                        <div style={{ width: '48px', height: '48px', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(99,102,241,0.1)', color: '#818cf8', borderRadius: '14px', border: '1px solid rgba(99,102,241,0.2)', padding: '10px' }}>
                            <BookOpen size={24} />
                        </div>
                        <div>
                            <h2 style={{ fontSize: '24px', fontWeight: 800, color: '#fff', margin: 0, letterSpacing: '-0.025em' }}>Study Archives</h2>
                            <p style={{ fontSize: '14px', color: '#64748b', margin: '4px 0 0' }}>Your collection of AI-architected learning paths</p>
                        </div>
                    </div>
                    <button
                        onClick={loadSavedPlans}
                        style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 18px', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', color: '#94a3b8', fontSize: '13px', fontWeight: 600, cursor: 'pointer', transition: 'all 0.2s' }}
                        onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'rgba(255,255,255,0.08)'; e.currentTarget.style.color = '#fff'; }}
                        onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'rgba(255,255,255,0.03)'; e.currentTarget.style.color = '#94a3b8'; }}
                    >
                        <RefreshCw size={16} className={loadingPlans ? "animate-spin" : ""} />
                        Synchronize
                    </button>
                </div>

                {loadingPlans ? (
                    <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '80px', textAlign: 'center' }}>
                        <Loader2 className="animate-spin" size={32} style={{ color: '#6366f1', marginBottom: '16px' }} />
                        <p style={{ color: '#64748b', fontSize: '14px', fontWeight: 500 }}>Decrypting your archives...</p>
                    </div>
                ) : savedPlans.length === 0 ? (
                    <div className="glass-card" style={{ padding: '80px', textAlign: 'center', borderStyle: 'dashed', borderWidth: '2px', borderColor: 'rgba(255,255,255,0.05)' }}>
                        <div style={{ width: '64px', height: '64px', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px', border: '1px solid rgba(255,255,255,0.05)' }}>
                            <Send size={24} style={{ color: '#334155' }} />
                        </div>
                        <h3 style={{ fontSize: '18px', fontWeight: 700, color: '#fff', margin: '0 0 8px' }}>Vault is Empty</h3>
                        <p style={{ fontSize: '14px', color: '#475569', margin: 0, maxWidth: '300px', marginLeft: 'auto', marginRight: 'auto' }}>Generate a custom roadmap above to populate your study library.</p>
                    </div>
                ) : (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '24px' }}>
                        {savedPlans.map((plan) => (
                            <div
                                key={plan._id}
                                className="glass-card"
                                style={{ padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', transition: 'all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)', cursor: 'default', minHeight: '220px', position: 'relative', overflow: 'hidden' }}
                                onMouseEnter={(e) => {
                                    e.currentTarget.style.transform = 'translateY(-8px) scale(1.02)';
                                    e.currentTarget.style.borderColor = 'rgba(99,102,241,0.4)';
                                    e.currentTarget.style.boxShadow = '0 20px 40px -15px rgba(0,0,0,0.5), 0 0 20px rgba(99,102,241,0.1)';
                                }}
                                onMouseLeave={(e) => {
                                    e.currentTarget.style.transform = 'translateY(0) scale(1)';
                                    e.currentTarget.style.borderColor = 'rgba(255,255,255,0.08)';
                                    e.currentTarget.style.boxShadow = '0 8px 32px 0 rgba(0, 0, 0, 0.3)';
                                }}
                            >
                                {/* Decorative Gradient Orb */}
                                <div style={{ position: 'absolute', top: '-20px', right: '-20px', width: '80px', height: '80px', background: 'radial-gradient(circle, rgba(99,102,241,0.15) 0%, transparent 70%)', borderRadius: '50%', pointerEvents: 'none' }} />

                                <div>
                                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
                                        <div style={{ display: 'flex', gap: '8px' }}>
                                            <span style={{ fontSize: '10px', fontWeight: 800, color: '#818cf8', backgroundColor: 'rgba(99,102,241,0.1)', padding: '4px 10px', borderRadius: '6px', textTransform: 'uppercase', letterSpacing: '0.05em', border: '1px solid rgba(99,102,241,0.2)' }}>
                                                {plan.subject}
                                            </span>
                                            <span style={{ fontSize: '10px', fontWeight: 800, color: '#94a3b8', backgroundColor: 'rgba(255,255,255,0.05)', padding: '4px 10px', borderRadius: '6px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                                                {plan.duration} Week{plan.duration !== 1 ? 's' : ''}
                                            </span>
                                        </div>
                                        <button
                                            onClick={() => handleDeletePlan(plan._id, plan.subject)}
                                            style={{ color: '#475569', backgroundColor: 'transparent', border: 'none', cursor: 'pointer', transition: 'all 0.2s', padding: '6px', borderRadius: '8px' }}
                                            onMouseEnter={(e) => { e.currentTarget.style.color = '#f43f5e'; e.currentTarget.style.backgroundColor = 'rgba(244,63,94,0.1)'; }}
                                            onMouseLeave={(e) => { e.currentTarget.style.color = '#475569'; e.currentTarget.style.backgroundColor = 'transparent'; }}
                                        >
                                            <Trash2 size={16} />
                                        </button>
                                    </div>
                                    <h3 style={{ fontSize: '18px', fontWeight: 700, color: '#fff', margin: '0 0 12px', lineHeight: 1.3 }}>{plan.title}</h3>
                                    <p style={{ fontSize: '13px', color: '#64748b', margin: 0, lineHeight: 1.6, opacity: 0.8, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                                        {plan.overview}
                                    </p>
                                </div>

                                <div style={{ marginTop: '24px', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                                    <div style={{ display: 'flex', gap: '4px' }}>
                                        {[1, 2, 3].map(i => (
                                            <div key={i} style={{ width: '12px', height: '3px', borderRadius: '2px', backgroundColor: i <= 2 ? '#6366f1' : 'rgba(255,255,255,0.1)' }} />
                                        ))}
                                    </div>
                                    <span style={{ fontSize: '11px', fontWeight: 600, color: '#334155', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Verified Roadmap</span>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};

export default AIPlanner;
